<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0 (Python 3.12.2 on win32)" generated="2024-08-04T10:38:58.880455" rpa="false" schemaversion="5">
<suite id="s1" name="Test Ddt Excel And Csv" source="C:\Users\One\Desktop\Robot_framework\testcases\test_ddt_excel_and_csv.robot">
<kw name="LaunchBrowser" owner="ddt_resource" type="SETUP">
<kw name="Open Browser" owner="SeleniumLibrary">
<msg time="2024-08-04T10:38:59.462502" level="INFO">Opening browser 'chrome' to base url 'https://practicetestautomation.com/practice-test-login/'.</msg>
<arg>${url}</arg>
<arg>${browser}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="PASS" start="2024-08-04T10:38:59.458886" elapsed="7.088779"/>
</kw>
<kw name="Maximize Browser Window" owner="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="PASS" start="2024-08-04T10:39:06.547665" elapsed="0.058590"/>
</kw>
<status status="PASS" start="2024-08-04T10:38:59.456894" elapsed="7.150440"/>
</kw>
<test id="s1-t1" name="Login with username ${username} and password ${password}" line="15">
<status status="FAIL" start="2024-08-04T10:39:06.609338" elapsed="0.002859">Test cannot be empty.</status>
</test>
<kw name="CloseBrowsers" owner="ddt_resource" type="TEARDOWN">
<kw name="Close All Browsers" owner="SeleniumLibrary">
<doc>Closes all open browsers and resets the browser cache.</doc>
<status status="PASS" start="2024-08-04T10:39:06.621410" elapsed="6.445804"/>
</kw>
<status status="PASS" start="2024-08-04T10:39:06.617865" elapsed="6.449349"/>
</kw>
<status status="FAIL" start="2024-08-04T10:38:58.885650" elapsed="14.181564"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Test Ddt Excel And Csv">Test Ddt Excel And Csv</stat>
</suite>
</statistics>
<errors>
<msg time="2024-08-04T10:38:59.449357" level="ERROR">Error in file 'C:\Users\One\Desktop\Robot_framework\testcases\test_ddt_excel_and_csv.robot' on line 5: Importing library 'DataDriver' failed: ModuleNotFoundError: No module named 'DataDriver'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\One\AppData\Roaming\JetBrains\PyCharmCE2023.3\plugins\robotframework-intellij\lib\robotframework_debug_adapter
  C:\Users\One\Desktop\Robot_framework
  C:\Users\One\AppData\Roaming\JetBrains\PyCharmCE2023.3\plugins\robotframework-intellij\lib
  C:\Users\One\AppData\Roaming\JetBrains\PyCharmCE2023.3\plugins\robotframework-intellij\lib\robotframework_ls\vendored
  C:\Users\One\AppData\Local\Programs\Python\Python312\python312.zip
  C:\Users\One\AppData\Local\Programs\Python\Python312\DLLs
  C:\Users\One\AppData\Local\Programs\Python\Python312\Lib
  C:\Users\One\AppData\Local\Programs\Python\Python312
  C:\Users\One\AppData\Local\Programs\Python\Python312\Lib\site-packages
  C:\Users\One\AppData\Local\Programs\Python\Python312\Lib\site-packages\win32
  C:\Users\One\AppData\Local\Programs\Python\Python312\Lib\site-packages\win32\lib
  C:\Users\One\AppData\Local\Programs\Python\Python312\Lib\site-packages\Pythonwin</msg>
</errors>
</robot>
